// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNwPdaWQZvnDpREslHgvcPlqiTYbhqePE',
    appId: '1:653999942770:web:c18b4666db269a9d5366eb',
    messagingSenderId: '653999942770',
    projectId: 'travelagentapp-5c995',
    authDomain: 'travelagentapp-5c995.firebaseapp.com',
    storageBucket: 'travelagentapp-5c995.appspot.com',
    measurementId: 'G-EDFMVBPK9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrcb2nrCT8w5yzFyRZJQWRXr23Q4t7TDI',
    appId: '1:653999942770:android:4c61551e13444ae35366eb',
    messagingSenderId: '653999942770',
    projectId: 'travelagentapp-5c995',
    storageBucket: 'travelagentapp-5c995.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPvLFccjJynMjRdGR2gQbAAbuLv0XKiBU',
    appId: '1:653999942770:ios:2cfa52c4e50bdec75366eb',
    messagingSenderId: '653999942770',
    projectId: 'travelagentapp-5c995',
    storageBucket: 'travelagentapp-5c995.appspot.com',
    iosBundleId: 'com.example.travelagentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPvLFccjJynMjRdGR2gQbAAbuLv0XKiBU',
    appId: '1:653999942770:ios:8b6f1ee28add33815366eb',
    messagingSenderId: '653999942770',
    projectId: 'travelagentapp-5c995',
    storageBucket: 'travelagentapp-5c995.appspot.com',
    iosBundleId: 'com.example.travelagentapp.RunnerTests',
  );
}
